import { Role, Branch, LMSUser, ChecklistRequirement } from '../types';
import { FormSchemaDefinition, LoanProductRecord } from '../types/formBuilderTypes';
import { ChargeConfigurationRecord } from '../types/chargeAdjustmentTypes';
import { ApprovalMatrixRule } from '../types/approvalTypes';
import { LoanProductConfig } from '../types/applicationTypes';

// ============================================================================
// Canonical Default Loan Application Form Schema Template
// ============================================================================
export const HOME_LOAN_FORM_SCHEMA: FormSchemaDefinition = {
  pages: [
    {
      id: 'page_personal',
      pageNumber: 1,
      title: 'Personal & Identity Information',
      description: 'Primary applicant legal identity and contact credentials',
      sections: [
        {
          id: 'sec_personal_1',
          title: 'Applicant Particulars',
          columns: 2,
          fields: [
            {
              id: 'applicant_full_name',
              type: 'TEXT',
              label: 'Applicant Full Legal Name',
              placeholder: 'As per PAN / Aadhaar Card',
              description: 'Enter your legal name exactly as shown on official government ID documents.',
              required: true,
              width: '1_COL',
              validation: { minLength: 3, maxLength: 80 },
            },
            {
              id: 'applicant_dob',
              type: 'DATE',
              label: 'Date of Birth',
              required: true,
              width: '1_COL',
            },
            {
              id: 'applicant_pan',
              type: 'TEXT',
              label: 'Permanent Account Number (PAN)',
              placeholder: 'ABCDE1234F',
              required: true,
              width: '1_COL',
              validation: {
                regexPattern: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$',
                customErrorMessage: 'Please enter a valid 10-character uppercase Indian PAN number (e.g. ABCDE1234F).',
              },
            },
            {
              id: 'applicant_mobile',
              type: 'PHONE',
              label: 'Primary Mobile Number',
              placeholder: '9876543210',
              required: true,
              width: '1_COL',
              validation: {
                regexPattern: '^[6-9][0-9]{9}$',
                customErrorMessage: 'Please enter a valid 10-digit Indian mobile number.',
              },
            },
            {
              id: 'applicant_email',
              type: 'EMAIL',
              label: 'Personal Email Address',
              placeholder: 'applicant@example.com',
              required: true,
              width: '1_COL',
            },
            {
              id: 'marital_status',
              type: 'SELECT',
              label: 'Marital Status',
              options: ['Single', 'Married', 'Divorced', 'Widowed'],
              required: true,
              width: '1_COL',
            },
          ],
        },
        {
          id: 'sec_personal_address',
          title: 'Residential Address',
          columns: 1,
          fields: [
            {
              id: 'current_address',
              type: 'ADDRESS',
              label: 'Current Residential Address (With PIN Code)',
              placeholder: 'Door No, Building, Street, City, State, PIN Code',
              description: 'Please provide the complete residential address where you currently reside.',
              required: true,
              width: 'FULL_WIDTH',
              validation: { minLength: 10, maxLength: 250 },
            },
          ],
        },
      ],
    },
    {
      id: 'page_employment',
      pageNumber: 2,
      title: 'Employment & Financial Profile',
      description: 'Income stream, employer credentials, and financial obligations',
      sections: [
        {
          id: 'sec_emp_1',
          title: 'Employment Background',
          columns: 2,
          fields: [
            {
              id: 'employment_type',
              type: 'SELECT',
              label: 'Employment Classification',
              options: ['Salaried', 'Self Employed Professional', 'Business Owner', 'Retired'],
              required: true,
              width: '1_COL',
            },
            {
              id: 'employer_name',
              type: 'TEXT',
              label: 'Company / Organization / Firm Name',
              placeholder: 'e.g. Infosys Ltd / Tech Solutions Pvt Ltd',
              required: true,
              width: '1_COL',
              condition: {
                dependentFieldId: 'employment_type',
                operator: 'NOT_EQUALS',
                triggerValue: 'Retired',
                action: 'SHOW',
              },
            },
            {
              id: 'monthly_net_income',
              type: 'CURRENCY',
              label: 'Net Monthly Take-Home Income (₹)',
              placeholder: '85,000',
              required: true,
              width: '1_COL',
              validation: { minValue: 15000 },
            },
            {
              id: 'existing_monthly_emis',
              type: 'CURRENCY',
              label: 'Existing Monthly Loan Obligations / EMIs (₹)',
              placeholder: '0',
              defaultValue: 0,
              required: true,
              width: '1_COL',
            },
          ],
        },
      ],
    },
    {
      id: 'page_property',
      pageNumber: 3,
      title: 'Property & Collateral Details',
      description: 'Collateral evaluation, location, and purchase estimation',
      sections: [
        {
          id: 'sec_property_1',
          title: 'Property Information',
          columns: 2,
          fields: [
            {
              id: 'property_type',
              type: 'SELECT',
              label: 'Property Type',
              options: ['Apartment / Flat', 'Independent Villa / House', 'Residential Plot + Construction', 'Commercial Shop'],
              required: true,
              width: '1_COL',
            },
            {
              id: 'property_stage',
              type: 'SELECT',
              label: 'Construction Stage',
              options: ['Ready to Move', 'Under Construction', 'Resale / Existing', 'Plot Purchase'],
              required: true,
              width: '1_COL',
            },
            {
              id: 'property_cost',
              type: 'CURRENCY',
              label: 'Total Agreement / Estimated Value (₹)',
              placeholder: '60,00,000',
              required: true,
              width: '1_COL',
              validation: { minValue: 500000 },
            },
            {
              id: 'requested_loan_amount',
              type: 'CURRENCY',
              label: 'Requested Home Loan Amount (₹)',
              placeholder: '48,00,000',
              required: true,
              width: '1_COL',
              validation: { minValue: 300000, maxValue: 50000000 },
            },
            {
              id: 'has_coapplicant',
              type: 'YES_NO',
              label: 'Do you wish to add a Co-applicant for higher loan eligibility?',
              defaultValue: 'No',
              required: true,
              width: 'FULL_WIDTH',
            },
            {
              id: 'coapplicant_name',
              type: 'TEXT',
              label: 'Co-applicant Full Name',
              placeholder: 'Spouse / Parent / Sibling Name',
              required: true,
              width: '1_COL',
              condition: {
                dependentFieldId: 'has_coapplicant',
                operator: 'EQUALS',
                triggerValue: 'Yes',
                action: 'SHOW',
              },
            },
            {
              id: 'coapplicant_income',
              type: 'CURRENCY',
              label: 'Co-applicant Monthly Income (₹)',
              placeholder: '50,000',
              width: '1_COL',
              condition: {
                dependentFieldId: 'has_coapplicant',
                operator: 'EQUALS',
                triggerValue: 'Yes',
                action: 'SHOW',
              },
            },
          ],
        },
      ],
    },
    {
      id: 'page_documents',
      pageNumber: 4,
      title: 'Document Uploads',
      description: 'Upload required verification files and property title papers',
      sections: [
        {
          id: 'sec_doc_1',
          title: 'Mandatory KYC & Income Documents',
          columns: 2,
          fields: [
            {
              id: 'doc_pan_card',
              type: 'FILE',
              label: 'PAN Card Copy (PDF / Image)',
              description: 'Clear color scan of physical PAN card.',
              required: true,
              width: '1_COL',
              validation: { acceptedFileTypes: ['.pdf', '.jpg', '.jpeg', '.png'], maxFileSizeMB: 5 },
            },
            {
              id: 'doc_salary_slips',
              type: 'FILE',
              label: 'Last 3 Months Salary Slips / Bank Statement',
              description: 'Official password-free PDF statements.',
              required: true,
              width: '1_COL',
              validation: { acceptedFileTypes: ['.pdf'], maxFileSizeMB: 10 },
            },
            {
              id: 'doc_property_agreement',
              type: 'FILE',
              label: 'Sale Agreement / Allotment Letter',
              description: 'Registered or draft builder agreement.',
              required: true,
              width: 'FULL_WIDTH',
              validation: { acceptedFileTypes: ['.pdf'], maxFileSizeMB: 15 },
            },
          ],
        },
      ],
    },
    {
      id: 'page_declaration',
      pageNumber: 5,
      title: 'Declaration & Digital Signature',
      description: 'Legal acknowledgment, credit bureau consent, and formal electronic signature',
      sections: [
        {
          id: 'sec_decl_1',
          title: 'Consent & Terms',
          columns: 1,
          fields: [
            {
              id: 'decl_terms',
              type: 'CHECKBOX',
              label: 'I confirm that all particulars stated in this application are true and correct to the best of my knowledge.',
              required: true,
              width: 'FULL_WIDTH',
            },
            {
              id: 'decl_cibil_consent',
              type: 'CHECKBOX',
              label: 'I authorize FinTech LMS and its lending partners to pull credit reports from CIBIL/Experian/Equifax/CRIF.',
              required: true,
              width: 'FULL_WIDTH',
            },
            {
              id: 'applicant_signature',
              type: 'SIGNATURE',
              label: 'Primary Applicant Digital Signature',
              description: 'Please sign within the box using your mouse, trackpad, or finger/stylus on touch screens.',
              required: true,
              width: 'FULL_WIDTH',
            },
          ],
        },
      ],
    },
  ],
  metadata: {
    productCode: 'HL-PRIME',
    productName: 'Home Loan Prime',
    estimatedCompletionMinutes: 10,
  },
  settings: {
    allowSaveDraft: true,
    requireSignature: true,
  },
};

// ============================================================================
// Baseline Loan Products Catalog
// ============================================================================
export const INITIAL_LOAN_PRODUCTS: LoanProductRecord[] = [
  {
    id: 'prod_hl_01',
    code: 'HL-PRIME',
    name: 'Home Loan Prime',
    category: 'HOUSING',
    description: 'Premier housing finance scheme for salaried and self-employed individuals with competitive reducing rates.',
    minAmount: 500000,
    maxAmount: 50000000,
    minTenureMonths: 60,
    maxTenureMonths: 360,
    baseInterestRate: 8.5,
    maxInterestRate: 11.0,
    interestMethod: 'REDUCING_BALANCE',
    repaymentFrequency: 'MONTHLY',
    processingFeePercent: 0.5,
    processingFeeFlat: 2500,
    documentationCharges: 1500,
    allowedFrequencies: ['MONTHLY'],
    requiredDocumentTypes: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'PROPERTY_TITLE'],
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 65,
      minMonthlyIncome: 30000,
      allowedEmploymentTypes: ['SALARIED', 'SELF_EMPLOYED', 'BUSINESS_OWNER'],
    },
    minCreditScore: 700,
    status: 'ACTIVE',
    version: 1,
    activeFormVersionId: 'form_ver_hl_01',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_pl_01',
    code: 'PL-EXEC',
    name: 'Express Personal Loan',
    category: 'PERSONAL',
    description: 'Instant unsecured personal credit for emergency, travel, wedding, and medical needs with fast approval.',
    minAmount: 50000,
    maxAmount: 2500000,
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: 12.5,
    maxInterestRate: 18.0,
    interestMethod: 'REDUCING_BALANCE',
    repaymentFrequency: 'MONTHLY',
    processingFeePercent: 1.5,
    processingFeeFlat: 1000,
    documentationCharges: 750,
    allowedFrequencies: ['MONTHLY'],
    requiredDocumentTypes: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT'],
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 58,
      minMonthlyIncome: 25000,
      allowedEmploymentTypes: ['SALARIED', 'PROFESSIONAL'],
    },
    minCreditScore: 680,
    status: 'ACTIVE',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_vl_01',
    code: 'VL-AUTO',
    name: 'Auto & Vehicle Loan',
    category: 'VEHICLE',
    description: 'Competitive vehicle financing for commercial and private passenger vehicles with up to 90% on-road funding.',
    minAmount: 100000,
    maxAmount: 5000000,
    minTenureMonths: 12,
    maxTenureMonths: 84,
    baseInterestRate: 9.25,
    maxInterestRate: 13.5,
    interestMethod: 'REDUCING_BALANCE',
    repaymentFrequency: 'MONTHLY',
    processingFeePercent: 1.0,
    processingFeeFlat: 1500,
    documentationCharges: 1000,
    allowedFrequencies: ['MONTHLY'],
    requiredDocumentTypes: ['PAN', 'AADHAAR', 'INCOME_PROOF', 'PROFORMA_INVOICE'],
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 65,
      minMonthlyIncome: 20000,
      allowedEmploymentTypes: ['SALARIED', 'SELF_EMPLOYED', 'BUSINESS_OWNER'],
    },
    minCreditScore: 660,
    status: 'ACTIVE',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod_bl_01',
    code: 'BL-SME',
    name: 'SME Business Growth Loan',
    category: 'BUSINESS',
    description: 'Working capital and term funding for registered MSMEs and expanding enterprises with flexible collateral.',
    minAmount: 200000,
    maxAmount: 10000000,
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: 13.0,
    maxInterestRate: 19.5,
    interestMethod: 'REDUCING_BALANCE',
    repaymentFrequency: 'MONTHLY',
    processingFeePercent: 2.0,
    processingFeeFlat: 5000,
    documentationCharges: 2500,
    allowedFrequencies: ['MONTHLY', 'QUARTERLY'],
    requiredDocumentTypes: ['GST_RETURNS', 'ITR_2_YEARS', 'BANK_STATEMENT_12M', 'BUSINESS_REGISTRATION'],
    eligibilityCriteria: {
      minAge: 25,
      maxAge: 65,
      minMonthlyIncome: 50000,
      allowedEmploymentTypes: ['BUSINESS_OWNER', 'SELF_EMPLOYED'],
    },
    minCreditScore: 650,
    status: 'ACTIVE',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const LOAN_PRODUCTS_CONFIG: LoanProductConfig[] = [
  {
    code: 'PROD-PL-001',
    name: 'Personal Loan - Prime Salaried',
    category: 'PERSONAL',
    description: 'Unsecured retail term financing for prime salaried professionals and executives.',
    minAmount: 50000,
    maxAmount: 1500000,
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: 12.5,
    allowedFrequencies: ['MONTHLY'],
    requiredDocumentTypes: [
      { type: 'IDENTITY_PROOF', title: 'Identity Verification (PAN / Aadhaar)', description: 'Government issued valid identity document.', isMandatory: true, canUseCustomerKyc: true },
      { type: 'ADDRESS_PROOF', title: 'Current Residential Address Proof', description: 'Utility bill, Aadhaar, or rental agreement within 3 months.', isMandatory: true, canUseCustomerKyc: true },
      { type: 'INCOME_SALARY_SLIP', title: 'Latest 3 Months Salary Slips', description: 'Employer issued salary pay slips with tax deductions.', isMandatory: true, canUseCustomerKyc: false },
      { type: 'BANK_STATEMENT', title: 'Salary Account Bank Statement (6 Months)', description: 'Bank e-statement showing salary credit transactions.', isMandatory: true, canUseCustomerKyc: false },
    ],
  },
  {
    code: 'PROD-HL-002',
    name: 'Housing Loan - Home Purchase & Construction',
    category: 'HOME',
    description: 'Secured residential property loan for ready-to-move purchase or self-construction.',
    minAmount: 500000,
    maxAmount: 25000000,
    minTenureMonths: 36,
    maxTenureMonths: 300,
    baseInterestRate: 8.65,
    allowedFrequencies: ['MONTHLY'],
    requiredDocumentTypes: [
      { type: 'IDENTITY_PROOF', title: 'Identity Verification (PAN / Aadhaar)', description: 'Government verified primary identity certificate.', isMandatory: true, canUseCustomerKyc: true },
      { type: 'ADDRESS_PROOF', title: 'Current Address Proof', description: 'Valid residential proof document.', isMandatory: true, canUseCustomerKyc: true },
      { type: 'PROPERTY_AGREEMENT', title: 'Registered Agreement for Sale / Title Chain', description: 'Copy of builder agreement or 13-year chain of title documents.', isMandatory: true, canUseCustomerKyc: false },
      { type: 'INCOME_TAX_RETURNS', title: 'ITR Returns & Form 16 (Last 2 Assessment Years)', description: 'ITR acknowledgement with computation of total taxable income.', isMandatory: true, canUseCustomerKyc: false },
      { type: 'BANK_STATEMENT', title: 'Bank Operating Account Statement (12 Months)', description: 'Full 12-month transaction trail for all primary bank accounts.', isMandatory: true, canUseCustomerKyc: false },
    ],
  },
];

// ============================================================================
// Standard System Charges Configurations
// ============================================================================
export const INITIAL_CHARGE_CONFIGURATIONS: ChargeConfigurationRecord[] = [
  {
    id: 'cfg_late_fee',
    chargeCode: 'LATE_FEE_MONTHLY',
    chargeName: 'Monthly Overdue / Late Payment Fee',
    chargeType: 'LATE_PAYMENT_FEE',
    calculationBasis: 'PERCENTAGE_OF_OVERDUE',
    rateOrValue: 2.0,
    taxPercentage: 18.0,
    minAmount: 500,
    maxAmount: 2500,
    applicableEvent: 'PAYMENT_LATE',
    isWaivable: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cfg_bounce_fee',
    chargeCode: 'BOUNCE_FEE_NACH',
    chargeName: 'NACH / e-Mandate Return Bounce Fee',
    chargeType: 'BOUNCE_FEE',
    calculationBasis: 'FIXED_AMOUNT',
    rateOrValue: 500,
    taxPercentage: 18.0,
    minAmount: 500,
    maxAmount: 500,
    applicableEvent: 'PAYMENT_RETURNED',
    isWaivable: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cfg_foreclosure_fee',
    chargeCode: 'FORECLOSURE_FEE_STD',
    chargeName: 'Standard Account Prepayment / Foreclosure Fee',
    chargeType: 'OTHER_FEE',
    calculationBasis: 'PERCENTAGE_OF_PRINCIPAL',
    rateOrValue: 3.0,
    taxPercentage: 18.0,
    minAmount: 1000,
    applicableEvent: 'EARLY_CLOSURE',
    isWaivable: false,
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

// ============================================================================
// Multi-Tier Approval Matrix Rules
// ============================================================================
export const INITIAL_APPROVAL_MATRIX_RULES: ApprovalMatrixRule[] = [
  {
    id: 'rule_pl_001',
    ruleCode: 'MAT-PL-L1-001',
    productCode: 'PROD-PL-001',
    productName: 'Personal Loan - Prime Salaried',
    minAmount: 0,
    maxAmount: 500000,
    branchId: 'ALL',
    branchName: 'All Pan-India Branches',
    region: 'ALL',
    level: 1,
    levelName: 'Level 1 — Branch Credit Review',
    approverRoleId: 'role_approver',
    approverRoleName: 'Branch Credit Manager',
    authorityLimit: 500000,
    canApproveExceptions: false,
    isActive: true,
    createdDate: '2025-01-01',
    updatedDate: '2026-01-10',
    updatedBy: 'System Administrator (EMP-001001)',
  },
  {
    id: 'rule_pl_002',
    ruleCode: 'MAT-PL-L2-002',
    productCode: 'PROD-PL-001',
    productName: 'Personal Loan - Prime Salaried',
    minAmount: 500001,
    maxAmount: 1500000,
    branchId: 'ALL',
    branchName: 'All Pan-India Branches',
    region: 'ALL',
    level: 2,
    levelName: 'Level 2 — Regional Credit Sanction',
    approverRoleId: 'role_regional_credit_manager',
    approverRoleName: 'Regional Credit Manager',
    authorityLimit: 1500000,
    canApproveExceptions: true,
    isActive: true,
    createdDate: '2025-01-01',
    updatedDate: '2026-01-10',
    updatedBy: 'System Administrator (EMP-001001)',
  },
];

// ============================================================================
// Baseline System Roles
// ============================================================================
export const INITIAL_ROLES: Role[] = [
  {
    id: 'role_sys_admin',
    code: 'SYSTEM_ADMIN',
    name: 'System Administrator',
    description: 'Full administrative access for user provisioning, security policies, branch network configuration, audit logs, and global parameter controls.',
    status: 'ACTIVE',
    userCount: 1,
    isSystemProtected: true,
    createdDate: '2025-01-01',
    updatedDate: '2026-02-15',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view', 'perm_cust_create', 'perm_cust_edit', 'perm_cust_export',
      'perm_kyc_view', 'perm_kyc_verify',
      'perm_app_view', 'perm_app_create', 'perm_app_edit', 'perm_app_submit', 'perm_app_cancel', 'perm_app_party_manage', 'perm_app_doc_view', 'perm_app_doc_upload', 'perm_app_doc_remove', 'perm_app_export',
      'perm_credit_view', 'perm_credit_conduct', 'perm_credit_recommend', 'perm_credit_assign', 'perm_credit_assess', 'perm_credit_edit', 'perm_credit_submit', 'perm_credit_return', 'perm_credit_decision', 'perm_credit_rule_view', 'perm_credit_condition_manage', 'perm_credit_history_view',
      'perm_appr_view', 'perm_appr_action', 'perm_appr_assign', 'perm_appr_reassign', 'perm_appr_decide', 'perm_appr_return', 'perm_appr_reject', 'perm_appr_condition_manage', 'perm_appr_exception_manage', 'perm_appr_history_view', 'perm_appr_matrix_view', 'perm_appr_matrix_manage', 'perm_appr_export',
      'perm_sanc_view', 'perm_sanc_create', 'perm_sanc_edit', 'perm_sanc_review', 'perm_sanc_confirm', 'perm_sanc_return', 'perm_sanc_cancel', 'perm_sanc_condition_manage', 'perm_sanc_letter_generate', 'perm_sanc_letter_issue', 'perm_sanc_history_view', 'perm_sanc_readiness_view', 'perm_sanc_readiness_manage',
      'perm_loan_view', 'perm_loan_close', 'perm_loan_foreclose',
      'perm_disb_view', 'perm_disb_execute',
      'perm_repay_view', 'perm_repay_post', 'perm_repay_reverse', 'perm_repay_waive',
      'perm_collec_view', 'perm_collec_action',
      'perm_rep_view', 'perm_rep_export',
      'perm_audit_view',
      'perm_users_view', 'perm_users_manage',
      'perm_roles_view', 'perm_roles_manage',
      'perm_branch_view', 'perm_branch_manage',
      'perm_sys_view', 'perm_sys_manage',
      'perm_prod_view', 'perm_prod_manage',
    ],
  },
  {
    id: 'role_loan_officer',
    code: 'LOAN_OFFICER',
    name: 'Loan Officer',
    description: 'Responsible for branch-level borrower sourcing, customer onboarding, KYC document intake, and initial loan application drafting and submission.',
    status: 'ACTIVE',
    userCount: 0,
    createdDate: '2025-01-10',
    updatedDate: '2026-01-20',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view', 'perm_cust_create', 'perm_cust_edit',
      'perm_kyc_view',
      'perm_app_view', 'perm_app_create', 'perm_app_edit', 'perm_app_submit', 'perm_app_party_manage', 'perm_app_doc_view', 'perm_app_doc_upload',
      'perm_sanc_view', 'perm_sanc_readiness_view',
      'perm_loan_view',
      'perm_repay_view',
      'perm_prod_view',
    ],
  },
  {
    id: 'role_credit_officer',
    code: 'CREDIT_OFFICER',
    name: 'Credit Officer',
    description: 'Conducts borrower credit assessments, financial analysis, bureau verification (CIBIL/Experian), and recommends sanction conditions.',
    status: 'ACTIVE',
    userCount: 0,
    createdDate: '2025-01-10',
    updatedDate: '2026-02-01',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view',
      'perm_kyc_view', 'perm_kyc_verify',
      'perm_app_view', 'perm_app_edit', 'perm_app_doc_view',
      'perm_credit_view', 'perm_credit_conduct', 'perm_credit_recommend', 'perm_credit_assign', 'perm_credit_assess', 'perm_credit_edit', 'perm_credit_submit', 'perm_credit_return', 'perm_credit_decision', 'perm_credit_rule_view', 'perm_credit_condition_manage', 'perm_credit_history_view',
      'perm_sanc_view', 'perm_sanc_history_view', 'perm_sanc_readiness_view',
      'perm_loan_view',
      'perm_prod_view',
    ],
  },
  {
    id: 'role_approver',
    code: 'BRANCH_CREDIT_MANAGER',
    name: 'Branch Credit Manager / Approver (Level 1)',
    description: 'Sanctioning authority for branch-level applications up to assigned delegation limit. Can approve, reject, or return applications.',
    status: 'ACTIVE',
    userCount: 0,
    createdDate: '2025-01-10',
    updatedDate: '2026-01-15',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view',
      'perm_kyc_view',
      'perm_app_view',
      'perm_credit_view',
      'perm_appr_view', 'perm_appr_action', 'perm_appr_assign', 'perm_appr_reassign', 'perm_appr_decide', 'perm_appr_return', 'perm_appr_reject', 'perm_appr_condition_manage', 'perm_appr_exception_manage', 'perm_appr_history_view', 'perm_appr_matrix_view',
      'perm_sanc_view', 'perm_sanc_create', 'perm_sanc_edit', 'perm_sanc_review', 'perm_sanc_confirm', 'perm_sanc_return', 'perm_sanc_condition_manage', 'perm_sanc_letter_generate', 'perm_sanc_letter_issue', 'perm_sanc_history_view', 'perm_sanc_readiness_view', 'perm_sanc_readiness_manage',
      'perm_loan_view',
      'perm_rep_view',
    ],
  },
  {
    id: 'role_regional_credit_manager',
    code: 'REGIONAL_CREDIT_MANAGER',
    name: 'Regional Credit Manager (Level 2)',
    description: 'Regional sanctioning authority for high-quantum retail and MSME loans. Authorizes exceptions routed from Level 1 branch reviewers.',
    status: 'ACTIVE',
    userCount: 0,
    createdDate: '2025-01-10',
    updatedDate: '2026-01-15',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view',
      'perm_kyc_view',
      'perm_app_view',
      'perm_credit_view',
      'perm_appr_view', 'perm_appr_action', 'perm_appr_assign', 'perm_appr_reassign', 'perm_appr_decide', 'perm_appr_return', 'perm_appr_reject', 'perm_appr_condition_manage', 'perm_appr_exception_manage', 'perm_appr_history_view', 'perm_appr_matrix_view',
      'perm_sanc_view', 'perm_sanc_create', 'perm_sanc_edit', 'perm_sanc_review', 'perm_sanc_confirm', 'perm_sanc_return', 'perm_sanc_cancel', 'perm_sanc_condition_manage', 'perm_sanc_letter_generate', 'perm_sanc_letter_issue', 'perm_sanc_history_view', 'perm_sanc_readiness_view', 'perm_sanc_readiness_manage',
      'perm_loan_view',
      'perm_rep_view',
    ],
  },
  {
    id: 'role_ops_officer',
    code: 'OPERATIONS_OFFICER',
    name: 'Operations Officer',
    description: 'Handles post-sanction documentation verification, bank account penny-drop checks, disbursement authorization, and loan account booking.',
    status: 'ACTIVE',
    userCount: 0,
    createdDate: '2025-01-10',
    updatedDate: '2026-02-10',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view',
      'perm_kyc_view',
      'perm_app_view',
      'perm_sanc_view', 'perm_sanc_readiness_view', 'perm_sanc_readiness_manage', 'perm_sanc_letter_issue',
      'perm_loan_view',
      'perm_disb_view', 'perm_disb_execute',
      'perm_repay_view', 'perm_repay_post',
      'perm_rep_view',
    ],
  },
  {
    id: 'role_management',
    code: 'MANAGEMENT',
    name: 'Management / Executive',
    description: 'Executive oversight role with read-only access to end-to-end portfolio KPIs, executive dashboards, regulatory compliance filings, and audit trails.',
    status: 'ACTIVE',
    userCount: 0,
    createdDate: '2025-01-10',
    updatedDate: '2026-02-05',
    updatedBy: 'System Administrator (EMP-001001)',
    permissionIds: [
      'perm_cust_view', 'perm_cust_export',
      'perm_app_view',
      'perm_credit_view',
      'perm_appr_view',
      'perm_sanc_view',
      'perm_loan_view',
      'perm_disb_view',
      'perm_repay_view',
      'perm_collec_view',
      'perm_rep_view', 'perm_rep_export',
      'perm_audit_view',
      'perm_branch_view',
      'perm_prod_view',
      'perm_sys_view',
    ],
  },
];

// ============================================================================
// Baseline System Branches
// ============================================================================
export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'br_panjim',
    code: 'BR-PNJ-001',
    name: 'Panaji Head Office Branch',
    addressLine1: 'Ground Floor, EDC Complex, Dr. Atmaram Borkar Road',
    addressLine2: 'Near Kadamba Bus Stand, Patto Plaza',
    city: 'Panaji',
    state: 'Goa',
    pinCode: '403001',
    phone: '0832-2420101',
    email: 'panaji.branch@fintechlms.in',
    managerId: 'usr_001',
    managerName: 'System Administrator',
    status: 'ACTIVE',
    userCount: 1,
    activeLoanCount: 0,
    totalPortfolioValue: 0,
    createdDate: '2025-01-01',
    updatedDate: '2026-02-10',
  },
  {
    id: 'br_mumbai_andheri',
    code: 'BR-MUM-004',
    name: 'Mumbai Andheri Corporate Hub',
    addressLine1: 'Unit 401, Solitaire Corporate Park, Andheri-Ghatkopar Link Road',
    addressLine2: 'Chakala, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    pinCode: '400093',
    phone: '022-68994500',
    email: 'mumbai.andheri@fintechlms.in',
    managerId: 'usr_001',
    managerName: 'System Administrator',
    status: 'ACTIVE',
    userCount: 0,
    activeLoanCount: 0,
    totalPortfolioValue: 0,
    createdDate: '2025-01-20',
    updatedDate: '2026-02-12',
  },
  {
    id: 'br_bengaluru_indira',
    code: 'BR-BLR-006',
    name: 'Bengaluru Indiranagar Tech Hub',
    addressLine1: '784, 100 Feet Road, HAL 2nd Stage',
    addressLine2: 'Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560038',
    phone: '080-41228700',
    email: 'blr.indiranagar@fintechlms.in',
    managerId: 'usr_001',
    managerName: 'System Administrator',
    status: 'ACTIVE',
    userCount: 0,
    activeLoanCount: 0,
    totalPortfolioValue: 0,
    createdDate: '2025-02-01',
    updatedDate: '2026-02-05',
  },
];

// ============================================================================
// Baseline System User (System Administrator)
// ============================================================================
export const INITIAL_USERS: LMSUser[] = [
  {
    id: 'usr_001',
    employeeId: 'EMP-001001',
    firstName: 'System',
    lastName: 'Admin',
    name: 'System Administrator',
    username: 'admin',
    email: 'admin@fintechlms.in',
    mobile: '9820144520',
    roleId: 'role_sys_admin',
    roleName: 'System Administrator',
    branchId: 'br_panjim',
    branchName: 'Panaji Head Office Branch',
    status: 'ACTIVE',
    department: 'Executive Administration & IT Security',
    createdDate: '2025-01-01',
    updatedDate: '2026-02-15',
    lastLogin: '2026-03-01 10:00 AM',
    failedLoginAttempts: 0,
  },
];

// ============================================================================
// Standard Document Checklist Requirements
// ============================================================================
export const INITIAL_CHECKLIST_REQUIREMENTS: ChecklistRequirement[] = [
  {
    id: 'req_pan',
    category: 'IDENTITY_PROOF',
    documentType: 'PAN_CARD',
    title: 'PAN Card (Permanent Account Number)',
    description: 'Mandatory primary government identity card for tax and credit bureau reporting.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL', 'BUSINESS'],
  },
  {
    id: 'req_aadhaar',
    category: 'ADDRESS_PROOF',
    documentType: 'AADHAAR_CARD',
    title: 'Aadhaar Card (UIDAI e-KYC / XML)',
    description: 'Officially Valid Document (OVD) for biometric and address verification.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL'],
  },
  {
    id: 'req_salary_slips',
    category: 'INCOME_PROOF',
    documentType: 'SALARY_SLIPS',
    title: 'Recent Salary Slips (Last 3 Months)',
    description: 'Detailed compensation and deduction statements from current employer.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL'],
    applicableLoanTypes: ['PERSONAL_LOAN', 'HOME_LOAN', 'AUTO_LOAN'],
    maxAgeDays: 90,
  },
  {
    id: 'req_bank_statement',
    category: 'BANKING_PROOF',
    documentType: 'BANK_STATEMENT',
    title: 'Bank Account Statements (Last 6 Months)',
    description: 'Operative bank statements reflecting regular salary credits or operational business turnover.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL', 'BUSINESS'],
    maxAgeDays: 180,
  },
  {
    id: 'req_form16_itr',
    category: 'INCOME_PROOF',
    documentType: 'FORM_16_ITR',
    title: 'Form 16 / Income Tax Returns (Last 2 Years)',
    description: 'Statutory income tax returns or employer Form 16 certificates with computed tax computation.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL', 'BUSINESS'],
  },
  {
    id: 'req_utility_bill',
    category: 'ADDRESS_PROOF',
    documentType: 'ELECTRICITY_UTILITY_BILL',
    title: 'Current Utility Bill (Electricity / Gas / Water)',
    description: 'Secondary address proof matching current residential or office premises (max 60 days old).',
    isMandatory: false,
    applicableCustomerTypes: ['INDIVIDUAL', 'BUSINESS'],
    maxAgeDays: 60,
  },
  {
    id: 'req_business_registration',
    category: 'BUSINESS_INCORPORATION',
    documentType: 'GST_UDYAM_CERTIFICATE',
    title: 'GST Certificate / Udyam MSME Registration',
    description: 'Official enterprise establishment certificate for business loans.',
    isMandatory: true,
    applicableCustomerTypes: ['BUSINESS'],
    applicableLoanTypes: ['BUSINESS_LOAN', 'WORKING_CAPITAL_LOAN'],
  },
  {
    id: 'req_property_title',
    category: 'COLLATERAL_PROPERTY',
    documentType: 'TITLE_DEED_NOC',
    title: 'Property Title Deed & Non-Encumbrance Certificate',
    description: 'Original registered sale deed and 13-year non-encumbrance certificate for secured lending.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL', 'BUSINESS'],
    applicableLoanTypes: ['HOME_LOAN', 'LOAN_AGAINST_PROPERTY'],
  },
  {
    id: 'req_photo',
    category: 'PHOTOGRAPH_SIGNATURE',
    documentType: 'PASSPORT_PHOTO_SIGNATURE',
    title: 'Passport Size Photograph & Wet Signature Specimen',
    description: 'High-resolution frontal portrait and official signing specimen.',
    isMandatory: true,
    applicableCustomerTypes: ['INDIVIDUAL'],
  },
];

