import { NavItem, NavGroup } from '../../types';

export const NAV_ITEMS: NavItem[] = [
  // Operations Group
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    group: 'Operations',
    iconName: 'LayoutDashboard',
    requiredPermission: 'view_dashboard',
  },
  {
    id: 'customers',
    label: 'Customers',
    path: '/customers',
    group: 'Operations',
    iconName: 'Users',
    requiredPermission: 'view_customers',
  },
  {
    id: 'kyc',
    label: 'KYC & Verification',
    path: '/kyc',
    group: 'Operations',
    iconName: 'ShieldCheck',
    requiredPermission: 'view_customers',
    badgeCount: 2,
  },
  {
    id: 'documents',
    label: 'Document Hub',
    path: '/documents',
    group: 'Operations',
    iconName: 'FolderOpen',
    requiredPermission: 'view_customers',
  },
  {
    id: 'applications',
    label: 'Applications',
    path: '/applications',
    group: 'Operations',
    iconName: 'FileText',
    requiredPermission: 'view_applications',
  },
  {
    id: 'disbursements',
    label: 'Disbursements',
    path: '/disbursements',
    group: 'Operations',
    iconName: 'Banknote',
    requiredPermission: 'view_disbursements',
    badgeCount: 2,
  },
  {
    id: 'loans',
    label: 'Loans',
    path: '/loans',
    group: 'Operations',
    iconName: 'Landmark',
    requiredPermission: 'view_loans',
  },
  {
    id: 'repayments',
    label: 'Repayments',
    path: '/repayments',
    group: 'Operations',
    iconName: 'CreditCard',
    requiredPermission: 'view_repayments',
  },
  {
    id: 'collections',
    label: 'Collections',
    path: '/collections',
    group: 'Operations',
    iconName: 'AlertOctagon',
    requiredPermission: 'view_collections',
    badgeCount: 2,
  },
  {
    id: 'recovery',
    label: 'Recovery & Legal',
    path: '/recovery',
    group: 'Operations',
    iconName: 'ShieldAlert',
    requiredPermission: 'view_collections',
    badgeCount: 3,
  },
  {
    id: 'restructuring',
    label: 'Restructuring',
    path: '/restructuring',
    group: 'Operations',
    iconName: 'RotateCcw',
    requiredPermission: 'view_loans',
  },
  {
    id: 'charges_adjustments',
    label: 'Charges & Waivers',
    path: '/charges-adjustments',
    group: 'Operations',
    iconName: 'DollarSign',
    requiredPermission: 'view_repayments',
  },
  {
    id: 'closures_noc',
    label: 'Closures & NOC',
    path: '/closures-noc',
    group: 'Operations',
    iconName: 'CheckCheck',
    requiredPermission: 'view_loans',
  },

  // Credit Group
  {
    id: 'credit_assessment',
    label: 'Credit Assessment',
    path: '/credit-assessment',
    group: 'Credit',
    iconName: 'ShieldCheck',
    requiredPermission: 'view_credit_assessment',
    badgeCount: 3,
  },
  {
    id: 'approvals',
    label: 'Approvals',
    path: '/approvals',
    group: 'Credit',
    iconName: 'CheckCircle2',
    requiredPermission: 'view_approvals',
    badgeCount: 4,
  },
  {
    id: 'sanctions',
    label: 'Sanctions',
    path: '/sanctions',
    group: 'Credit',
    iconName: 'FileCheck',
    requiredPermission: 'view_sanctions',
  },

  // Configuration Group
  {
    id: 'loan_products',
    label: 'Loan Products',
    path: '/loan-products',
    group: 'Configuration',
    iconName: 'Layers',
    requiredPermission: 'view_loan_products',
  },
  {
    id: 'users',
    label: 'User Management',
    path: '/users',
    group: 'Configuration',
    iconName: 'Users',
    requiredPermission: 'manage_users_roles',
  },
  {
    id: 'roles',
    label: 'Roles & Permissions',
    path: '/roles',
    group: 'Configuration',
    iconName: 'Shield',
    requiredPermission: 'manage_users_roles',
  },
  {
    id: 'branches',
    label: 'Branch Management',
    path: '/branches',
    group: 'Configuration',
    iconName: 'Building',
    requiredPermission: 'manage_users_roles',
  },
  {
    id: 'system_config',
    label: 'App & System Settings',
    path: '/system-config',
    group: 'Configuration',
    iconName: 'Settings',
    requiredPermission: 'view_system_config',
  },
  {
    id: 'admin',
    label: 'Administration',
    path: '/admin',
    group: 'Configuration',
    iconName: 'ShieldCheck',
    requiredPermission: 'manage_users_roles',
  },

  // Reports Group
  {
    id: 'reports',
    label: 'Reports',
    path: '/reports',
    group: 'Reports',
    iconName: 'BarChart3',
    requiredPermission: 'view_reports',
  },
  {
    id: 'audit',
    label: 'Audit',
    path: '/audit',
    group: 'Reports',
    iconName: 'History',
    requiredPermission: 'view_audit',
  },
];

export const NAV_GROUPS: NavGroup[] = ['Operations', 'Credit', 'Configuration', 'Reports'];
